 export const featuredProducts = [
  {
    id: "1",
    name: "Traditional Daura Suruwal",
    price: 4500,
    originalPrice: 5500,
    image: "/images/food.jpg",
    rating: 4.5,
    reviews: 128,
    seller: "Heritage Crafts Nepal",
    category: "clothes",
    inStock: true,
    fastDelivery: true,
  },
  {
    id: "2",
    name: "Himalayan Honey (1kg)",
    price: 1200,
    originalPrice: 1500,
    image: "/images/handicraft.jpg",
    rating: 4.8,
    reviews: 89,
    seller: "Mountain Bee Farm",
    category: "food",
    inStock: true,
    fastDelivery: false,
  },
  {
    id: "3",
    name: "Hand-carved Wooden Mask",
    price: 2800,
    originalPrice: 3200,
    image: "/images/food.jpg",
    rating: 4.6,
    reviews: 45,
    seller: "Kathmandu Crafts",
    category: "handicrafts",
    inStock: true,
    fastDelivery: true,
  },

  {
    id: "5",
    name: "Singing Bowl Set",
    price: 3500,
    originalPrice: 4000,
    image: "/images/food.jpg",
    rating: 4.7,
    reviews: 92,
    seller: "Himalayan Sounds",
    category: "handicrafts",
    inStock: true,
    fastDelivery: true,
  },
  {
    id: "6",
    name: "Yak Cheese (500g)",
    price: 1800,
    originalPrice: 2200,
    image: "/images/food.jpg",
    rating: 4.4,
    reviews: 34,
    seller: "Mountain Dairy",
    category: "food",
    inStock: true,
    fastDelivery: false,
  },
];